"""empty message

Revision ID: 5a367d8bb6d4
Revises: 4f9962b7606f
Create Date: 2021-07-24 13:54:54.426567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a367d8bb6d4'
down_revision = '4f9962b7606f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traders', sa.Column('is_subdealer', sa.Integer(), nullable=True))
    op.add_column('traders_temp', sa.Column('is_subdealer', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('sd_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'traders', ['sd_id'], ['id'])
    op.add_column('transactions_temp', sa.Column('sd_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions_temp', 'traders', ['sd_id'], ['id'])
    op.add_column('trpl', sa.Column('sd_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trpl', 'traders', ['sd_id'], ['id'])
    op.add_column('trpl_temp', sa.Column('sd_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trpl_temp', 'traders', ['sd_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trpl_temp', type_='foreignkey')
    op.drop_column('trpl_temp', 'sd_id')
    op.drop_constraint(None, 'trpl', type_='foreignkey')
    op.drop_column('trpl', 'sd_id')
    op.drop_constraint(None, 'transactions_temp', type_='foreignkey')
    op.drop_column('transactions_temp', 'sd_id')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'sd_id')
    op.drop_column('traders_temp', 'is_subdealer')
    op.drop_column('traders', 'is_subdealer')
    # ### end Alembic commands ###
