"""empty message

Revision ID: b2b54a7d084f
Revises: 689284445e2e
Create Date: 2021-10-02 17:01:37.709178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b54a7d084f'
down_revision = '689284445e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redemption', sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redemption', 'date_modified')
    # ### end Alembic commands ###
