"""empty message

Revision ID: 689284445e2e
Revises: 5a367d8bb6d4
Create Date: 2021-10-02 14:36:18.048636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689284445e2e'
down_revision = '5a367d8bb6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redemption', sa.Column('recipient_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redemption', 'recipient_image')
    # ### end Alembic commands ###
